### ISSUE TITLE
Invoice With Header configure example is not working 

### ISSUE THREAD

**Issue by CoolM1234** [jsreport/jsreport-dotnet-example-net-webapp#1]
![capture](https://user-images.githubusercontent.com/30105375/30958492-ed80b764-a46f-11e7-9e76-e2e656f7a763.PNG)

Any one know how to slove it? pls help
thanks

**Comment by pofider** [comment]
I fixed the demo. The correct way to set header is

```cs
HttpContext.JsReportFeature()
                .Recipe(Recipe.PhantomPdf)
                .Configure((r) => r.Template.Phantom = new Phantom { Header = this.RenderViewToString("Header", new { }) });

```

**Comment by CoolM1234** [comment]
Thanks~ the problem is solved :) :+1:
